### ISSUE TITLE
Homebrew reports deprecation warning for plist_options:

### ISSUE THREAD

**Issue by brokenjacobs** [kcaebe/homebrew-dns-heaven#1]
```
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the kcaebe/dns-heaven tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/kcaebe/homebrew-dns-heaven/Formula/dns-heaven.rb:36
```

https://github.com/kcaebe/homebrew-dns-heaven/blob/2c4e42a8810810c98689ba1f2822d92dbfe9bd4a/Formula/dns-heaven.rb#L36

**Comment by brokenjacobs** [comment]
Looks like homebrew has a new 'service' class that can be used:
https://github.com/Homebrew/brew/blob/58f7cb0d4e53db4df85d167b780cece0fef6762c/Library/Homebrew/service.rb

**Comment by kcaebe** [comment]
I finally got around to making updates for this, this should be resolved now.
